version: '3.4'

services:
  educationsearchv3:
    container_name: EducationSearchWebApi
    image: ${DOCKER_REGISTRY-}educationsearchv3
    build:
      context: .
      dockerfile: EducationSearchV3/Dockerfile
    ports:
      - ${APP_PORT}:80
      - ${APP_PORT_S}:443
    depends_on:
      - ms-sql-server

  ms-sql-server:
    container_name: MSSQL
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_USER: ${DB_MSSQL_USER}
      MSSQL_PASSWORD: ${DB_MSSQL_PASSWORD}
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:
