name: Build and test pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out new code
        uses: actions/checkout@v3

      - name: Setup .Net6
        uses: actions/setup-dotnet@v1.0.0
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore EducationSearchV3.sln

      - name: Build
        run: dotnet build EducationSearchV3.sln -c Release --no-restore

      - name: Run tests
        run: dotnet test EducationSearchV3.sln -c Release --no-build